footer marking/3 button
meretska-sofiia/project-html-css pull request #7
Opened 2022-08-10 18:47 UTC by ssvyatoss

2022-08-10 19:14 UTC, meretska-sofiia requested changes

2022-08-10 19:14 UTC, meretska-sofiia commented on src/partials/footer.html
> +      <ul class="navigation-list">
<a href="" class="logo">
            <svg class="logo-img" width="40" height="40">
                <use href="../images/sprite#logo-icon"></use>
            </svg>
        </a>

2022-08-10 19:14 UTC, meretska-sofiia commented on src/partials/footer.html
> +    <form name="subscribe-modal" class="subscribe-modal">
убираем нейм

2022-08-10 19:14 UTC, meretska-sofiia commented on src/partials/footer.html
> +        <span class="footer__subscribe-title">Subscribe</span>
убрать спан и подпись засунуть в лейбл

2022-08-10 19:14 UTC, meretska-sofiia commented on src/partials/footer.html
> +        <button type="submit" class="button">Subscribe</button>
лейбл заканчивается после инпута

2022-08-10 19:14 UTC, meretska-sofiia commented on src/partials/footer.html
> +        <span class="privacy-policy"
р

2022-08-10 19:14 UTC, meretska-sofiia commented on src/sass/base/_placeholder.scss
> +    width: 100px;
min-width

2022-08-10 19:14 UTC, meretska-sofiia commented on src/sass/base/_placeholder.scss
> +    width: 106px;
min-width

2022-08-10 19:14 UTC, meretska-sofiia commented on src/sass/index.css
> +ul,
удалить

2022-08-11 07:22 UTC, meretska-sofiia approved these changes

2022-08-11 07:23 UTC, merged

2022-08-11 07:28 UTC, ssvyatoss commented on src/partials/footer.html
> +        <span class="footer__subscribe-title">Subscribe</span>
В лейбл окрім класів текстовий контент не засовується, тобто span потрібен щоб його стилізувати.

2022-08-11 07:28 UTC, ssvyatoss commented on src/partials/footer.html
> +      <ul class="navigation-list">
+

2022-08-11 07:28 UTC, ssvyatoss commented on src/partials/footer.html
> +    <form name="subscribe-modal" class="subscribe-modal">
+

2022-08-11 07:28 UTC, ssvyatoss commented on src/partials/footer.html
> +        <button type="submit" class="button">Subscribe</button>
+

2022-08-11 07:28 UTC, ssvyatoss commented on src/partials/footer.html
> +        <span class="privacy-policy"
+